/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LogrosRouteImport } from './routes/logros'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosCourseIdRouteImport } from './routes/cursos.$courseId'
import { Route as PracticarIndexRouteImport } from './routes/practicar.index'
import { Route as PracticarSesionRouteImport } from './routes/practicar.sesion'
import { Route as SimulacroIndexRouteImport } from './routes/simulacro.index'
import { Route as SimulacroResultadoRouteImport } from './routes/simulacro.resultado'
import { Route as SimulacroSesionRouteImport } from './routes/simulacro.sesion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LogrosRoute = LogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosCourseIdRoute = CursosCourseIdRouteImport.update({
  id: '/cursos/$courseId',
  path: '/cursos/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticarIndexRoute = PracticarIndexRouteImport.update({
  id: '/practicar/',
  path: '/practicar/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticarSesionRoute = PracticarSesionRouteImport.update({
  id: '/practicar/sesion',
  path: '/practicar/sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacroIndexRoute = SimulacroIndexRouteImport.update({
  id: '/simulacro/',
  path: '/simulacro/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacroResultadoRoute = SimulacroResultadoRouteImport.update({
  id: '/simulacro/resultado',
  path: '/simulacro/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacroSesionRoute = SimulacroSesionRouteImport.update({
  id: '/simulacro/sesion',
  path: '/simulacro/sesion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/estadisticas': typeof EstadisticasRoute
  '/home': typeof HomeRoute
  '/logros': typeof LogrosRoute
  '/perfil': typeof PerfilRoute
  '/cursos/$courseId': typeof CursosCourseIdRoute
  '/practicar/sesion': typeof PracticarSesionRoute
  '/simulacro/resultado': typeof SimulacroResultadoRoute
  '/simulacro/sesion': typeof SimulacroSesionRoute
  '/cursos/': typeof CursosIndexRoute
  '/practicar/': typeof PracticarIndexRoute
  '/simulacro/': typeof SimulacroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/estadisticas': typeof EstadisticasRoute
  '/home': typeof HomeRoute
  '/logros': typeof LogrosRoute
  '/perfil': typeof PerfilRoute
  '/cursos/$courseId': typeof CursosCourseIdRoute
  '/practicar/sesion': typeof PracticarSesionRoute
  '/simulacro/resultado': typeof SimulacroResultadoRoute
  '/simulacro/sesion': typeof SimulacroSesionRoute
  '/cursos': typeof CursosIndexRoute
  '/practicar': typeof PracticarIndexRoute
  '/simulacro': typeof SimulacroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/estadisticas': typeof EstadisticasRoute
  '/home': typeof HomeRoute
  '/logros': typeof LogrosRoute
  '/perfil': typeof PerfilRoute
  '/cursos/$courseId': typeof CursosCourseIdRoute
  '/practicar/sesion': typeof PracticarSesionRoute
  '/simulacro/resultado': typeof SimulacroResultadoRoute
  '/simulacro/sesion': typeof SimulacroSesionRoute
  '/cursos/': typeof CursosIndexRoute
  '/practicar/': typeof PracticarIndexRoute
  '/simulacro/': typeof SimulacroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracion'
    | '/estadisticas'
    | '/home'
    | '/logros'
    | '/perfil'
    | '/cursos/$courseId'
    | '/practicar/sesion'
    | '/simulacro/resultado'
    | '/simulacro/sesion'
    | '/cursos/'
    | '/practicar/'
    | '/simulacro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracion'
    | '/estadisticas'
    | '/home'
    | '/logros'
    | '/perfil'
    | '/cursos/$courseId'
    | '/practicar/sesion'
    | '/simulacro/resultado'
    | '/simulacro/sesion'
    | '/cursos'
    | '/practicar'
    | '/simulacro'
  id:
    | '__root__'
    | '/'
    | '/configuracion'
    | '/estadisticas'
    | '/home'
    | '/logros'
    | '/perfil'
    | '/cursos/$courseId'
    | '/practicar/sesion'
    | '/simulacro/resultado'
    | '/simulacro/sesion'
    | '/cursos/'
    | '/practicar/'
    | '/simulacro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EstadisticasRoute: typeof EstadisticasRoute
  HomeRoute: typeof HomeRoute
  LogrosRoute: typeof LogrosRoute
  PerfilRoute: typeof PerfilRoute
  CursosCourseIdRoute: typeof CursosCourseIdRoute
  PracticarSesionRoute: typeof PracticarSesionRoute
  SimulacroResultadoRoute: typeof SimulacroResultadoRoute
  SimulacroSesionRoute: typeof SimulacroSesionRoute
  CursosIndexRoute: typeof CursosIndexRoute
  PracticarIndexRoute: typeof PracticarIndexRoute
  SimulacroIndexRoute: typeof SimulacroIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logros': {
      id: '/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof LogrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$courseId': {
      id: '/cursos/$courseId'
      path: '/cursos/$courseId'
      fullPath: '/cursos/$courseId'
      preLoaderRoute: typeof CursosCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicar/': {
      id: '/practicar/'
      path: '/practicar'
      fullPath: '/practicar/'
      preLoaderRoute: typeof PracticarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practicar/sesion': {
      id: '/practicar/sesion'
      path: '/practicar/sesion'
      fullPath: '/practicar/sesion'
      preLoaderRoute: typeof PracticarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacro/': {
      id: '/simulacro/'
      path: '/simulacro'
      fullPath: '/simulacro/'
      preLoaderRoute: typeof SimulacroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacro/resultado': {
      id: '/simulacro/resultado'
      path: '/simulacro/resultado'
      fullPath: '/simulacro/resultado'
      preLoaderRoute: typeof SimulacroResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacro/sesion': {
      id: '/simulacro/sesion'
      path: '/simulacro/sesion'
      fullPath: '/simulacro/sesion'
      preLoaderRoute: typeof SimulacroSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EstadisticasRoute: EstadisticasRoute,
  HomeRoute: HomeRoute,
  LogrosRoute: LogrosRoute,
  PerfilRoute: PerfilRoute,
  CursosCourseIdRoute: CursosCourseIdRoute,
  PracticarSesionRoute: PracticarSesionRoute,
  SimulacroResultadoRoute: SimulacroResultadoRoute,
  SimulacroSesionRoute: SimulacroSesionRoute,
  CursosIndexRoute: CursosIndexRoute,
  PracticarIndexRoute: PracticarIndexRoute,
  SimulacroIndexRoute: SimulacroIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
